### ISSUE TITLE
Parsing of tables (data request)

### ISSUE THREAD

**Issue by mandresm** [esm-tools/pymorize#18]
Builds the data request information from the tables, making sure there is not variable repetition and correct merging of the information spread across the different tables.

https://github.com/FESOM/seamore/blob/7725366f7b68ea3824ac6baa500ea49531722b72/lib/data_request.rb#L7

The file consists in 4 classes:
- [x] `DataRequest`: responsible for managing variables and their associated metadata across **multiple CMIP6 tables**.
     - [x] Frequency mappings: map a frequency name with a numeric frequency (maybe this is better in a separate file?
- [x] `DataRequestVariable`: represents a single variable and its associated metadata. It can merge multiple `TableVarEntry`s into `DataRequestVariable` object
- [x] `TableVarEntry`: represents a **single** entry for a variable in a table.
- [x] `DataRequestTable`: represents a single CMIP6 table and its metadata.

The overall design ensures that variables are merged correctly across multiple tables, providing a unified interface to query variables and their metadata.

### Crappy ~UML
```mermaid
flowchart LR

    subgraph DataRequest
        subgraph DRinitialize[initialize]
            direction TB
            table_initialization
            --> var_initialization
            --> for_vars[for v in vars]
            --> if_v_exists[    if v exists]
            --> if_v_!exists[    else]
        end
    end
    subgraph DataRequestVariable
        new_from_table_var_entry
        --> DRVinitialize[initialize]
        merge_table_var_entry
    end
    subgraph TableVarEntry
        TVEinitialize[initialize]
    end
    subgraph DataRequestTable
        DRTinitialize[initialize]
        variable_entries
    end

    table_initialization --> DRTinitialize
    var_initialization --> variable_entries
    variable_entries --> TVEinitialize
    if_v_exists --> merge_table_var_entry
    if_v_!exists --> new_from_table_var_entry
```

**Comment by pgierz** [comment]
I have some design questions about this, in particular how it will fit into the rest of our current config structure. Currently we have the following, and some of what I write down here will need to end up in the handbook (which I nominate @chrisdane and @christian-stepanek to improve upon once I draft it, since user-facing documentation is best written by early test users)

```yaml
pymorize:
   # ... program metadata and settings for the program itself ...
general:  # (Or global, we haven't decided the name yet)
   # ... Information that will always be relevant
pipelines:
   # ... collections of steps to apply ...
rules:
   # ... list of rules (see below) ...
```

The `rules` section is the main part the users will need to deal with. It is a list of dictionaries, and maps a collection of user files to a CMOR variable. A typical rule might look like this:

```yaml
rules:
    - cmor_variable: so
      model_variable: salt
      cmor_units: PSU
      model_units: PSU  # Can be omitted if NetCDF meta-data is complete. If given, value
                        # in the rules sections will win over what is in the NetCDF, always.
      file_patterns:
          - /a/pattern/with/fesom.salt.(Pyear/d+).*nc  # Use Python-extended regex, **not**
                                                       # globbing!!!
```

The rules specification is a work-in-progress, and not set in stone (yet). Still to be considered are output files, variables that end up in multiple files (time aggregation), CMOR variables that depend on multiple inputs...
